import { MigrationInterface, QueryRunner } from "typeorm";

export class CompleteMigration1775073888426 implements MigrationInterface {
    name = 'CompleteMigration1775073888426'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_SESSIONS_USER"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_AUDIT_LOGS_USER"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_PASSWORD_RESET_TOKENS_USER"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_USERS_ROLE"`);
        await queryRunner.query(`ALTER TABLE "machine_documents" DROP CONSTRAINT "fk_machine_docs_machine"`);
        await queryRunner.query(`ALTER TABLE "maintenance_plans" DROP CONSTRAINT "fk_maint_plans_machine"`);
        await queryRunner.query(`ALTER TABLE "work_order_parts" DROP CONSTRAINT "fk_wop_work_order"`);
        await queryRunner.query(`ALTER TABLE "breakdown_records" DROP CONSTRAINT "fk_br_work_order"`);
        await queryRunner.query(`ALTER TABLE "breakdown_records" DROP CONSTRAINT "fk_br_machine"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "fk_work_orders_machine"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "fk_work_orders_plan"`);
        await queryRunner.query(`ALTER TABLE "inspection_criteria" DROP CONSTRAINT "fk_insp_criteria_point"`);
        await queryRunner.query(`ALTER TABLE "inspection_records" DROP CONSTRAINT "fk_insp_records_point"`);
        await queryRunner.query(`ALTER TABLE "inspection_records" DROP CONSTRAINT "fk_insp_records_inspector"`);
        await queryRunner.query(`ALTER TABLE "non_conformities" DROP CONSTRAINT "fk_nc_detected_by"`);
        await queryRunner.query(`ALTER TABLE "nc_root_causes" DROP CONSTRAINT "fk_nc_root_causes_nc"`);
        await queryRunner.query(`ALTER TABLE "corrective_actions" DROP CONSTRAINT "fk_corrective_actions_nc"`);
        await queryRunner.query(`ALTER TABLE "corrective_actions" DROP CONSTRAINT "fk_corrective_actions_assigned"`);
        await queryRunner.query(`ALTER TABLE "corrective_actions" DROP CONSTRAINT "fk_corrective_actions_verified"`);
        await queryRunner.query(`ALTER TABLE "quality_decisions" DROP CONSTRAINT "fk_quality_decisions_nc"`);
        await queryRunner.query(`ALTER TABLE "quality_decisions" DROP CONSTRAINT "fk_quality_decisions_approved"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ROLES_NAME"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSIONS_TOKEN_HASH"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSIONS_EXPIRES_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_LOGS_ACTION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_LOGS_MODULE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_LOGS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PASSWORD_RESET_TOKENS_HASH"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PASSWORD_RESET_TOKENS_EXPIRES"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_EMAIL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_IS_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."idx_profiles_reference"`);
        await queryRunner.query(`DROP INDEX "public"."idx_profiles_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_profiles_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_customers_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_customers_company"`);
        await queryRunner.query(`DROP INDEX "public"."idx_customers_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_machine_docs_machine"`);
        await queryRunner.query(`DROP INDEX "public"."idx_maint_plans_machine"`);
        await queryRunner.query(`DROP INDEX "public"."idx_maint_plans_next_due"`);
        await queryRunner.query(`DROP INDEX "public"."idx_maint_plans_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wop_work_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wop_part"`);
        await queryRunner.query(`DROP INDEX "public"."idx_br_work_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_br_machine"`);
        await queryRunner.query(`DROP INDEX "public"."idx_br_reported"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wo_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wo_machine"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wo_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wo_priority"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wo_assigned"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wo_scheduled"`);
        await queryRunner.query(`DROP INDEX "public"."idx_machines_designation"`);
        await queryRunner.query(`DROP INDEX "public"."idx_machines_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_machines_serial"`);
        await queryRunner.query(`DROP INDEX "public"."idx_insp_points_stage"`);
        await queryRunner.query(`DROP INDEX "public"."idx_insp_points_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_insp_criteria_point"`);
        await queryRunner.query(`DROP INDEX "public"."idx_insp_criteria_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_insp_records_point"`);
        await queryRunner.query(`DROP INDEX "public"."idx_insp_records_inspector"`);
        await queryRunner.query(`DROP INDEX "public"."idx_insp_records_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_insp_records_result"`);
        await queryRunner.query(`DROP INDEX "public"."idx_insp_records_production"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_severity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_lot"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_detected_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_detected_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_rc_nc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_rc_method"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_rc_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nc_rc_analyzed_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ca_nc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ca_assigned"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ca_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ca_due_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_qd_nc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_qd_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_qd_decision_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_qd_approved_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_requests_employee"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attendances_employee_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payslips_employee_period"`);
        await queryRunner.query(`DROP INDEX "public"."idx_performance_reviews_employee"`);
        await queryRunner.query(`DROP INDEX "public"."idx_employees_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_employees_department"`);
        await queryRunner.query(`DROP INDEX "public"."idx_employees_hire_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recruitment_candidates_job"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "reorder_quantity" integer`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "minimum_order_quantity" integer`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "aluminum_profiles" ALTER COLUMN "density" SET DEFAULT '2.700'`);
        await queryRunner.query(`ALTER TABLE "departments" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "departments" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "departments" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."contract_type_enum" RENAME TO "contract_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_contracts_contract_type_enum" AS ENUM('CDI', 'CDD', 'STAGE', 'APPRENTICE', 'INTERIM')`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "contract_type" TYPE "public"."employee_contracts_contract_type_enum" USING "contract_type"::"text"::"public"."employee_contracts_contract_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."contract_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."contract_status_enum" RENAME TO "contract_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_contracts_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'TERMINATED')`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "status" TYPE "public"."employee_contracts_status_enum" USING "status"::"text"::"public"."employee_contracts_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."contract_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."leave_type_enum" RENAME TO "leave_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_leave_type_enum" AS ENUM('ANNUAL', 'SICK', 'MATERNITY', 'PATERNITY', 'UNPAID', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "leave_type" TYPE "public"."leave_requests_leave_type_enum" USING "leave_type"::"text"::"public"."leave_requests_leave_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leave_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_status_enum" RENAME TO "leave_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "status" TYPE "public"."leave_requests_status_enum" USING "status"::"text"::"public"."leave_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."leave_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."attendance_status_enum" RENAME TO "attendance_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."attendances_status_enum" AS ENUM('PRESENT', 'ABSENT', 'LATE', 'ON_LEAVE')`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "status" TYPE "public"."attendances_status_enum" USING "status"::"text"::"public"."attendances_status_enum"`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "status" SET DEFAULT 'PRESENT'`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "overtime_pay" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "bonuses" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "deductions" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."payslip_status_enum" RENAME TO "payslip_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payslips_status_enum" AS ENUM('DRAFT', 'VALIDATED', 'PAID')`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "status" TYPE "public"."payslips_status_enum" USING "status"::"text"::"public"."payslips_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."payslip_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."review_status_enum" RENAME TO "review_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."performance_reviews_status_enum" AS ENUM('DRAFT', 'SUBMITTED', 'COMPLETED')`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "status" TYPE "public"."performance_reviews_status_enum" USING "status"::"text"::"public"."performance_reviews_status_enum"`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."review_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trainings" ALTER COLUMN "is_mandatory" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trainings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trainings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."training_session_status_enum" RENAME TO "training_session_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."training_sessions_status_enum" AS ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "status" TYPE "public"."training_sessions_status_enum" USING "status"::"text"::"public"."training_sessions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "status" SET DEFAULT 'SCHEDULED'`);
        await queryRunner.query(`DROP TYPE "public"."training_session_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."enrollment_status_enum" RENAME TO "enrollment_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."training_enrollments_status_enum" AS ENUM('ENROLLED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "status" TYPE "public"."training_enrollments_status_enum" USING "status"::"text"::"public"."training_enrollments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "status" SET DEFAULT 'ENROLLED'`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "postes" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "postes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "postes" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_postes" ALTER COLUMN "is_primary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_postes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "country" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."employee_status_enum" RENAME TO "employee_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'TERMINATED', 'ON_LEAVE')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" TYPE "public"."employees_status_enum" USING "status"::"text"::"public"."employees_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."employee_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."recruitment_job_status_enum" RENAME TO "recruitment_job_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_jobs_status_enum" AS ENUM('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "status" TYPE "public"."recruitment_jobs_status_enum" USING "status"::"text"::"public"."recruitment_jobs_status_enum"`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_job_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."candidate_status_enum" RENAME TO "candidate_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_candidates_status_enum" AS ENUM('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "status" TYPE "public"."recruitment_candidates_status_enum" USING "status"::"text"::"public"."recruitment_candidates_status_enum"`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "status" SET DEFAULT 'APPLIED'`);
        await queryRunner.query(`DROP TYPE "public"."candidate_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_e89b545fe9935b650a3e86722f" ON "departments" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_8681da666ad9699d568b3e9106" ON "departments" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_91fddbe23e927e1e525c152baa" ON "departments" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_971bf5e2176b2bbabff7e4cbd7" ON "employee_contracts" ("start_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7950806b38a16f8378ac241f7" ON "employee_contracts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_764f83b1ad1017c0210a5ab362" ON "employee_contracts" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fcb0b127d834a3aeb9b1563f49" ON "leave_requests" ("end_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_434c95f48764657f78d5081471" ON "leave_requests" ("start_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9cc5df6df50aed58f4d84aa4f" ON "leave_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_52b4b7c7d295e204add6dbe0a0" ON "leave_requests" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_69fb1c5e3dc1d2f3171f6e6025" ON "attendances" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4cb05e42312bf271450939c361" ON "attendances" ("attendance_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_43dca8b4751d7449a38b583991" ON "attendances" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f717b99e28266bcc697fd6bc1" ON "payslips" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c936b3236b4c6a846bcd981832" ON "payslips" ("period_year", "period_month") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ca6cde51127cd649278d038ca" ON "payslips" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b92b3b23bff5510b9355ded584" ON "performance_reviews" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f00d6c73b1579cf8b74be67837" ON "performance_reviews" ("review_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d11995817c8d382fb313dc46c" ON "performance_reviews" ("reviewer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d1d9e46c9f01ac7c07d59b275" ON "performance_reviews" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_42d38d439c9fc4d0813f549226" ON "training_sessions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4b3e7ed64047bf340a3926eeb" ON "training_sessions" ("scheduled_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc91e635469fc770497e61f336" ON "training_sessions" ("training_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_edd7ab1f9c91329abbb0978aca" ON "training_enrollments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d06b58957e66b7537f2973c30" ON "training_enrollments" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f3e6ad2eaa08adfca73d493d0" ON "training_enrollments" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ab1b33ee656e3fa77bed622b3" ON "postes" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_e06798ee2713021df0a1377206" ON "postes" ("department_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ad8dc6bd6929dbcab71e0a07eb" ON "postes" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f35cd16752e46dd59e38e60b4" ON "employee_postes" ("is_primary") `);
        await queryRunner.query(`CREATE INDEX "IDX_87df6a17b05ee005a08520b7a8" ON "employee_postes" ("poste_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3fe5645a5209610145ddb3e144" ON "employee_postes" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9abb988d172effc1caff99b4ea" ON "employees" ("hire_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_678a3540f843823784b0fe4a4f" ON "employees" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_faa35befc241081a6b05010396" ON "employees" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_765bc1ac8967533a04c74a9f6a" ON "employees" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8878710dc844ecd6f9e587f34f" ON "employees" ("employee_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_85687048bc1f5ba06cec4ec445" ON "recruitment_jobs" ("publish_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_85d61c2003b28fbe8b0f51dae5" ON "recruitment_jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1685f589a58971749182a0bffb" ON "recruitment_jobs" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7a7c3edc70c2d2959ff2359ef" ON "recruitment_candidates" ("application_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9f96501eb63a9c3355204a79a" ON "recruitment_candidates" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_09bcb093afa9904234c9d2383c" ON "recruitment_candidates" ("job_id") `);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_ef8a4fb89ff96bbe98f1798798c" FOREIGN KEY ("manager_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_2d6673ae91cee09bef47d2a5de2" FOREIGN KEY ("parent_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ADD CONSTRAINT "FK_764f83b1ad1017c0210a5ab3624" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_52b4b7c7d295e204add6dbe0a09" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_c46c950aa343c4598ed7042c1b7" FOREIGN KEY ("approver_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_43dca8b4751d7449a38b583991c" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payslips" ADD CONSTRAINT "FK_3ca6cde51127cd649278d038ca9" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ADD CONSTRAINT "FK_2d1d9e46c9f01ac7c07d59b2756" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ADD CONSTRAINT "FK_2d11995817c8d382fb313dc46cf" FOREIGN KEY ("reviewer_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ADD CONSTRAINT "FK_dc91e635469fc770497e61f3369" FOREIGN KEY ("training_id") REFERENCES "trainings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ADD CONSTRAINT "FK_5f3e6ad2eaa08adfca73d493d02" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ADD CONSTRAINT "FK_9d06b58957e66b7537f2973c30a" FOREIGN KEY ("session_id") REFERENCES "training_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "postes" ADD CONSTRAINT "FK_e06798ee2713021df0a1377206e" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_postes" ADD CONSTRAINT "FK_3fe5645a5209610145ddb3e1441" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_postes" ADD CONSTRAINT "FK_87df6a17b05ee005a08520b7a84" FOREIGN KEY ("poste_id") REFERENCES "postes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_678a3540f843823784b0fe4a4f2" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ADD CONSTRAINT "FK_1685f589a58971749182a0bffb3" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ADD CONSTRAINT "FK_09bcb093afa9904234c9d2383cb" FOREIGN KEY ("job_id") REFERENCES "recruitment_jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" DROP CONSTRAINT "FK_09bcb093afa9904234c9d2383cb"`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" DROP CONSTRAINT "FK_1685f589a58971749182a0bffb3"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_678a3540f843823784b0fe4a4f2"`);
        await queryRunner.query(`ALTER TABLE "employee_postes" DROP CONSTRAINT "FK_87df6a17b05ee005a08520b7a84"`);
        await queryRunner.query(`ALTER TABLE "employee_postes" DROP CONSTRAINT "FK_3fe5645a5209610145ddb3e1441"`);
        await queryRunner.query(`ALTER TABLE "postes" DROP CONSTRAINT "FK_e06798ee2713021df0a1377206e"`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" DROP CONSTRAINT "FK_9d06b58957e66b7537f2973c30a"`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" DROP CONSTRAINT "FK_5f3e6ad2eaa08adfca73d493d02"`);
        await queryRunner.query(`ALTER TABLE "training_sessions" DROP CONSTRAINT "FK_dc91e635469fc770497e61f3369"`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" DROP CONSTRAINT "FK_2d11995817c8d382fb313dc46cf"`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" DROP CONSTRAINT "FK_2d1d9e46c9f01ac7c07d59b2756"`);
        await queryRunner.query(`ALTER TABLE "payslips" DROP CONSTRAINT "FK_3ca6cde51127cd649278d038ca9"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_43dca8b4751d7449a38b583991c"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_c46c950aa343c4598ed7042c1b7"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_52b4b7c7d295e204add6dbe0a09"`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" DROP CONSTRAINT "FK_764f83b1ad1017c0210a5ab3624"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_2d6673ae91cee09bef47d2a5de2"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_ef8a4fb89ff96bbe98f1798798c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09bcb093afa9904234c9d2383c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9f96501eb63a9c3355204a79a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7a7c3edc70c2d2959ff2359ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1685f589a58971749182a0bffb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85d61c2003b28fbe8b0f51dae5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85687048bc1f5ba06cec4ec445"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8878710dc844ecd6f9e587f34f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_765bc1ac8967533a04c74a9f6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faa35befc241081a6b05010396"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_678a3540f843823784b0fe4a4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9abb988d172effc1caff99b4ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fe5645a5209610145ddb3e144"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87df6a17b05ee005a08520b7a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f35cd16752e46dd59e38e60b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad8dc6bd6929dbcab71e0a07eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e06798ee2713021df0a1377206"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ab1b33ee656e3fa77bed622b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f3e6ad2eaa08adfca73d493d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d06b58957e66b7537f2973c30"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edd7ab1f9c91329abbb0978aca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc91e635469fc770497e61f336"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4b3e7ed64047bf340a3926eeb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42d38d439c9fc4d0813f549226"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d1d9e46c9f01ac7c07d59b275"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d11995817c8d382fb313dc46c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f00d6c73b1579cf8b74be67837"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b92b3b23bff5510b9355ded584"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ca6cde51127cd649278d038ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c936b3236b4c6a846bcd981832"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f717b99e28266bcc697fd6bc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43dca8b4751d7449a38b583991"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4cb05e42312bf271450939c361"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69fb1c5e3dc1d2f3171f6e6025"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52b4b7c7d295e204add6dbe0a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9cc5df6df50aed58f4d84aa4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_434c95f48764657f78d5081471"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcb0b127d834a3aeb9b1563f49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_764f83b1ad1017c0210a5ab362"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7950806b38a16f8378ac241f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_971bf5e2176b2bbabff7e4cbd7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91fddbe23e927e1e525c152baa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8681da666ad9699d568b3e9106"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e89b545fe9935b650a3e86722f"`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_status_enum_old" AS ENUM('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "status" TYPE "public"."candidate_status_enum_old" USING "status"::"text"::"public"."candidate_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "recruitment_candidates" ALTER COLUMN "status" SET DEFAULT 'APPLIED'`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_candidates_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."candidate_status_enum_old" RENAME TO "candidate_status_enum"`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_job_status_enum_old" AS ENUM('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "status" TYPE "public"."recruitment_job_status_enum_old" USING "status"::"text"::"public"."recruitment_job_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "recruitment_jobs" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_jobs_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."recruitment_job_status_enum_old" RENAME TO "recruitment_job_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."employee_status_enum_old" AS ENUM('ACTIVE', 'INACTIVE', 'TERMINATED', 'ON_LEAVE')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" TYPE "public"."employee_status_enum_old" USING "status"::"text"::"public"."employee_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."employees_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employee_status_enum_old" RENAME TO "employee_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "country" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_postes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_postes" ALTER COLUMN "is_primary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "postes" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "postes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "postes" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_status_enum_old" AS ENUM('ENROLLED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "status" TYPE "public"."enrollment_status_enum_old" USING "status"::"text"::"public"."enrollment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ALTER COLUMN "status" SET DEFAULT 'ENROLLED'`);
        await queryRunner.query(`DROP TYPE "public"."training_enrollments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."enrollment_status_enum_old" RENAME TO "enrollment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."training_session_status_enum_old" AS ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "status" TYPE "public"."training_session_status_enum_old" USING "status"::"text"::"public"."training_session_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ALTER COLUMN "status" SET DEFAULT 'SCHEDULED'`);
        await queryRunner.query(`DROP TYPE "public"."training_sessions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."training_session_status_enum_old" RENAME TO "training_session_status_enum"`);
        await queryRunner.query(`ALTER TABLE "trainings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trainings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trainings" ALTER COLUMN "is_mandatory" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."review_status_enum_old" AS ENUM('DRAFT', 'SUBMITTED', 'COMPLETED')`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "status" TYPE "public"."review_status_enum_old" USING "status"::"text"::"public"."review_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."performance_reviews_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."review_status_enum_old" RENAME TO "review_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payslip_status_enum_old" AS ENUM('DRAFT', 'VALIDATED', 'PAID')`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "status" TYPE "public"."payslip_status_enum_old" USING "status"::"text"::"public"."payslip_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."payslips_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payslip_status_enum_old" RENAME TO "payslip_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "deductions" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "bonuses" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payslips" ALTER COLUMN "overtime_pay" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_enum_old" AS ENUM('PRESENT', 'ABSENT', 'LATE', 'ON_LEAVE')`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "status" TYPE "public"."attendance_status_enum_old" USING "status"::"text"::"public"."attendance_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "attendances" ALTER COLUMN "status" SET DEFAULT 'PRESENT'`);
        await queryRunner.query(`DROP TYPE "public"."attendances_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."attendance_status_enum_old" RENAME TO "attendance_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."leave_status_enum_old" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "status" TYPE "public"."leave_status_enum_old" USING "status"::"text"::"public"."leave_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_status_enum_old" RENAME TO "leave_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_type_enum_old" AS ENUM('ANNUAL', 'SICK', 'MATERNITY', 'PATERNITY', 'UNPAID', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ALTER COLUMN "leave_type" TYPE "public"."leave_type_enum_old" USING "leave_type"::"text"::"public"."leave_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_leave_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_type_enum_old" RENAME TO "leave_type_enum"`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."contract_status_enum_old" AS ENUM('ACTIVE', 'EXPIRED', 'TERMINATED')`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "status" TYPE "public"."contract_status_enum_old" USING "status"::"text"::"public"."contract_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."employee_contracts_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."contract_status_enum_old" RENAME TO "contract_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."contract_type_enum_old" AS ENUM('CDI', 'CDD', 'STAGE', 'APPRENTICE', 'INTERIM')`);
        await queryRunner.query(`ALTER TABLE "employee_contracts" ALTER COLUMN "contract_type" TYPE "public"."contract_type_enum_old" USING "contract_type"::"text"::"public"."contract_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."employee_contracts_contract_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."contract_type_enum_old" RENAME TO "contract_type_enum"`);
        await queryRunner.query(`ALTER TABLE "departments" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "departments" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "departments" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aluminum_profiles" ALTER COLUMN "density" SET DEFAULT 2.700`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "minimum_order_quantity"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "reorder_quantity"`);
        await queryRunner.query(`CREATE INDEX "idx_recruitment_candidates_job" ON "recruitment_candidates" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "idx_employees_hire_date" ON "employees" ("hire_date") `);
        await queryRunner.query(`CREATE INDEX "idx_employees_department" ON "employees" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "idx_employees_status" ON "employees" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_performance_reviews_employee" ON "performance_reviews" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payslips_employee_period" ON "payslips" ("employee_id", "period_month", "period_year") `);
        await queryRunner.query(`CREATE INDEX "idx_attendances_employee_date" ON "attendances" ("attendance_date", "employee_id") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_requests_status" ON "leave_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_requests_employee" ON "leave_requests" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "idx_qd_approved_by" ON "quality_decisions" ("approved_by") `);
        await queryRunner.query(`CREATE INDEX "idx_qd_decision_type" ON "quality_decisions" ("decision_type") `);
        await queryRunner.query(`CREATE INDEX "idx_qd_status" ON "quality_decisions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_qd_nc" ON "quality_decisions" ("nc_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ca_due_date" ON "corrective_actions" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "idx_ca_status" ON "corrective_actions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_ca_assigned" ON "corrective_actions" ("assigned_to") `);
        await queryRunner.query(`CREATE INDEX "idx_ca_nc" ON "corrective_actions" ("nc_id") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_rc_analyzed_by" ON "nc_root_causes" ("analyzed_by") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_rc_category" ON "nc_root_causes" ("category") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_rc_method" ON "nc_root_causes" ("method") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_rc_nc" ON "nc_root_causes" ("nc_id") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_detected_at" ON "non_conformities" ("detected_at") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_detected_by" ON "non_conformities" ("detected_by") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_lot" ON "non_conformities" ("lot_number") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_severity" ON "non_conformities" ("severity") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_status" ON "non_conformities" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_nc_number" ON "non_conformities" ("nc_number") `);
        await queryRunner.query(`CREATE INDEX "idx_insp_records_production" ON "inspection_records" ("production_order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_insp_records_result" ON "inspection_records" ("result") `);
        await queryRunner.query(`CREATE INDEX "idx_insp_records_status" ON "inspection_records" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_insp_records_inspector" ON "inspection_records" ("inspector_id") `);
        await queryRunner.query(`CREATE INDEX "idx_insp_records_point" ON "inspection_records" ("inspection_point_id") `);
        await queryRunner.query(`CREATE INDEX "idx_insp_criteria_active" ON "inspection_criteria" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_insp_criteria_point" ON "inspection_criteria" ("inspection_point_id") `);
        await queryRunner.query(`CREATE INDEX "idx_insp_points_active" ON "inspection_points" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_insp_points_stage" ON "inspection_points" ("production_stage") `);
        await queryRunner.query(`CREATE INDEX "idx_machines_serial" ON "machines" ("serial_number") `);
        await queryRunner.query(`CREATE INDEX "idx_machines_status" ON "machines" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_machines_designation" ON "machines" ("designation") `);
        await queryRunner.query(`CREATE INDEX "idx_wo_scheduled" ON "work_orders" ("scheduled_date") `);
        await queryRunner.query(`CREATE INDEX "idx_wo_assigned" ON "work_orders" ("assigned_to") `);
        await queryRunner.query(`CREATE INDEX "idx_wo_priority" ON "work_orders" ("priority") `);
        await queryRunner.query(`CREATE INDEX "idx_wo_status" ON "work_orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_wo_machine" ON "work_orders" ("machine_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wo_number" ON "work_orders" ("work_order_number") `);
        await queryRunner.query(`CREATE INDEX "idx_br_reported" ON "breakdown_records" ("reported_at") `);
        await queryRunner.query(`CREATE INDEX "idx_br_machine" ON "breakdown_records" ("machine_id") `);
        await queryRunner.query(`CREATE INDEX "idx_br_work_order" ON "breakdown_records" ("work_order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wop_part" ON "work_order_parts" ("part_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wop_work_order" ON "work_order_parts" ("work_order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_maint_plans_active" ON "maintenance_plans" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_maint_plans_next_due" ON "maintenance_plans" ("next_due_date") `);
        await queryRunner.query(`CREATE INDEX "idx_maint_plans_machine" ON "maintenance_plans" ("machine_id") `);
        await queryRunner.query(`CREATE INDEX "idx_machine_docs_machine" ON "machine_documents" ("machine_id") `);
        await queryRunner.query(`CREATE INDEX "idx_customers_active" ON "customers" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_customers_company" ON "customers" ("company_name") `);
        await queryRunner.query(`CREATE INDEX "idx_customers_code" ON "customers" ("code") `);
        await queryRunner.query(`CREATE INDEX "idx_profiles_active" ON "aluminum_profiles" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_profiles_type" ON "aluminum_profiles" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_profiles_reference" ON "aluminum_profiles" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_IS_ACTIVE" ON "users" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_EMAIL" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_PASSWORD_RESET_TOKENS_EXPIRES" ON "password_reset_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_PASSWORD_RESET_TOKENS_HASH" ON "password_reset_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_LOGS_CREATED_AT" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_LOGS_MODULE" ON "audit_logs" ("module") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_LOGS_ACTION" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSIONS_EXPIRES_AT" ON "sessions" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSIONS_TOKEN_HASH" ON "sessions" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_ROLES_NAME" ON "roles" ("name") `);
        await queryRunner.query(`ALTER TABLE "quality_decisions" ADD CONSTRAINT "fk_quality_decisions_approved" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_decisions" ADD CONSTRAINT "fk_quality_decisions_nc" FOREIGN KEY ("nc_id") REFERENCES "non_conformities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "corrective_actions" ADD CONSTRAINT "fk_corrective_actions_verified" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "corrective_actions" ADD CONSTRAINT "fk_corrective_actions_assigned" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "corrective_actions" ADD CONSTRAINT "fk_corrective_actions_nc" FOREIGN KEY ("nc_id") REFERENCES "non_conformities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nc_root_causes" ADD CONSTRAINT "fk_nc_root_causes_nc" FOREIGN KEY ("nc_id") REFERENCES "non_conformities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "non_conformities" ADD CONSTRAINT "fk_nc_detected_by" FOREIGN KEY ("detected_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inspection_records" ADD CONSTRAINT "fk_insp_records_inspector" FOREIGN KEY ("inspector_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inspection_records" ADD CONSTRAINT "fk_insp_records_point" FOREIGN KEY ("inspection_point_id") REFERENCES "inspection_points"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inspection_criteria" ADD CONSTRAINT "fk_insp_criteria_point" FOREIGN KEY ("inspection_point_id") REFERENCES "inspection_points"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "fk_work_orders_plan" FOREIGN KEY ("maintenance_plan_id") REFERENCES "maintenance_plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "fk_work_orders_machine" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "breakdown_records" ADD CONSTRAINT "fk_br_machine" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "breakdown_records" ADD CONSTRAINT "fk_br_work_order" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_parts" ADD CONSTRAINT "fk_wop_work_order" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_plans" ADD CONSTRAINT "fk_maint_plans_machine" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "machine_documents" ADD CONSTRAINT "fk_machine_docs_machine" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_USERS_ROLE" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_PASSWORD_RESET_TOKENS_USER" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_AUDIT_LOGS_USER" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_SESSIONS_USER" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
